baseURL = 'https://totallynotdavid.github.io/galaxia/'
languageCode = 'es'
DefaultContentLanguage = 'es'
title = 'Galaxia'

comments = true

[pagination]
  perPage = 10

[taxonomies]
  tag = "tags"

[permalinks]
  tags = "/tags/:slug"