title = 'Galaxia'
search = true

## JSON-LD
schemaType = "Organization"
schemaName = "Galaxia"
schemaAuthor = "David Duran"
schemaAuthorGitHub = "https://github.com/totallynotdavid"

# Edit Page
repoHost = "GitHub"
docsRepo = "https://github.com/totallynotdavid/galaxia"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = true
lastMod = true