title = 'Galaxia'
search = true
comments = true

# Edit Page
repoHost = "GitHub"
docsRepo = "https://github.com/totallynotdavid/galaxia"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = true
lastMod = true

[seo]
  [seo.title]
    separator = " | "
    suffix = ""
  [seo.favicons]
    sizes = []
    icon = "favicon.png"
    svgIcon = "favicon.svg"
    maskIcon = "mask-icon.svg"
    maskIconColor = "white" # white (default)
  [seo.schemas]
    type = "Person"
    logo = "favicon-512x512.png"
    name = "David Duran"
    sameAs = ["https://github.com/totallynotdavid/"]
    images = ["cover.png"]
    blogPosting = ["blog"]
