name: URL Health Check

on: [push]

jobs:
    check-links:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: atalent-labs/404-links@3.1.3
              env:
                  GITHUB_TOKEN: ${{ secrets.LINK_CHECK_404 }}
